# Generated by Django 4.0.1 on 2022-01-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batting_innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField()),
                ('not_out', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystats.player')),
            ],
        ),
    ]
