# Generated by Django 4.0.1 on 2022-02-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystats', '0002_batting_innings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=10),
        ),
    ]
